apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shortner
  name: url-shortner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortner
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          effect: "NoSchedule"
          operator: "Exists"
      nodeSelector:
        pool-name: default
      containers:
        - name: url-shortner
          image: odessa0510/assignment3:url-shortner
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred



